apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - image: nginx
      name: nginx-pod-image

  volumes:
    - name: logs-volume
      hostPath:
        path: /var/log/nginx
        type: Directory
