apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-apache-deployment
  labels:
    app: nginx-apache-deployment
    type: front-end
spec:
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
