apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
      app: nginx-pod
spec:
  containers:
  - name: apache-container
    image: httpd:latest
    resources:
      requests:
        memory: "1Gi"   
        cpu: "900m"       
      limits:
        memory: "1Gi"    
        cpu: "1"          
